<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{eedc87b0-498f-42a3-9add-b62d0d4a527c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[AutomationLibrary();
Visualaisation_Control();
RobotPosTracker();
Object_State();
Automatic_Mode();
Automatic_Mode_Control_Panel();
Manual_Mode_Control_Panel();
Manual_Mode();
Pause_System();
Manual_Auto();
Deactivate();
Prompts();
State_Of_Station();]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="77" Count="8" />
      <LineId Id="75" Count="0" />
      <LineId Id="89" Count="0" />
      <LineId Id="93" Count="0" />
      <LineId Id="97" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>